import Header from '@/components/Header';
import '../styles/main.scss';
import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Footer from '@/components/Footer';
import Hero from '@/components/Hero';
import Logos from '@/components/Logos';
import FormContact from '@/components/FormContact';

const ubuntu = Ubuntu({ weight: ['300', '400', '500', '700'], subsets: ['latin-ext'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className} id="outer-container">
        <Header />
        <Hero />
        <Logos />
        <main id="page-wrap">{children}</main>
        <FormContact />
        <Footer />
      </body>
    </html>
  );
}
